# Generated by Django 3.2.4 on 2021-08-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('tel', models.IntegerField(verbose_name='телефон')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('house', models.PositiveIntegerField(verbose_name='дом')),
                ('building', models.CharField(max_length=5, verbose_name='строение')),
                ('entrance', models.PositiveIntegerField(verbose_name='подъезд')),
                ('flat', models.PositiveIntegerField(verbose_name='квартира')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Курьеры',
                'verbose_name_plural': 'Курьеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('info_post', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пост главной страницы',
                'verbose_name_plural': 'Пост главной страницы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=255, verbose_name='Вещь')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Questions_And_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_question', models.TextField(blank=True, verbose_name='Вопрос')),
                ('аnswer_question', models.TextField(blank=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопросы и ответы',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_reviews', models.TextField(blank=True, verbose_name='Отзыв')),
                ('client_id_reviews', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.client', verbose_name='ID Клиента Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзыв',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.BooleanField(default=True)),
                ('clientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.client', verbose_name='ID Клиента')),
                ('courierId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.courier', verbose_name='ID Курьера')),
                ('priceId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.prices', verbose_name='ID Заказа')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
    ]
